"""Public package exports for Hypercap CC NLP."""

from .analysis_core import (
    binary_crosstab_yes_no,
    classify_icd_category_vectorized,
    classify_inclusion_type_vectorized,
    ensure_required_columns,
    resolve_analysis_paths,
    symptom_distribution_by_overlap,
    to_binary_flag,
)
from .cohort_quality import (
    DEFAULT_VITALS_MODEL_RANGES,
    EXPECTED_STRUCTURAL_NULL_FIELDS,
    add_vitals_model_fields,
    attach_closest_pre_ed_omr,
    assert_gas_source_coverage,
    build_first_other_pco2_audit,
    classify_missingness_expectations,
    evaluate_uom_expectations,
    prepare_omr_records,
    summarize_gas_source,
)
from .rater_core import build_r3_nlp_join_audit, normalize_join_keys
from .workflow_contracts import (
    CANONICAL_COHORT_FILENAME,
    CANONICAL_NLP_FILENAME,
    CLASSIFIER_TRANSITIONAL_ALIASES,
    DATA_DIRNAME,
    PRIOR_RUNS_DIRNAME,
    data_dir,
    ensure_required_columns as ensure_required_workflow_columns,
    normalize_classifier_input_schema,
    resolve_analysis_input_path,
    resolve_classifier_input_path,
    resolve_classifier_output_paths,
    resolve_rater_nlp_input_path,
)

__all__ = [
    "binary_crosstab_yes_no",
    "classify_icd_category_vectorized",
    "classify_inclusion_type_vectorized",
    "ensure_required_columns",
    "ensure_required_workflow_columns",
    "EXPECTED_STRUCTURAL_NULL_FIELDS",
    "DEFAULT_VITALS_MODEL_RANGES",
    "CANONICAL_COHORT_FILENAME",
    "CANONICAL_NLP_FILENAME",
    "CLASSIFIER_TRANSITIONAL_ALIASES",
    "DATA_DIRNAME",
    "PRIOR_RUNS_DIRNAME",
    "data_dir",
    "add_vitals_model_fields",
    "attach_closest_pre_ed_omr",
    "assert_gas_source_coverage",
    "build_r3_nlp_join_audit",
    "build_first_other_pco2_audit",
    "classify_missingness_expectations",
    "evaluate_uom_expectations",
    "normalize_classifier_input_schema",
    "normalize_join_keys",
    "prepare_omr_records",
    "resolve_analysis_input_path",
    "resolve_classifier_input_path",
    "resolve_classifier_output_paths",
    "resolve_rater_nlp_input_path",
    "resolve_analysis_paths",
    "summarize_gas_source",
    "symptom_distribution_by_overlap",
    "to_binary_flag",
]
